// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alarms.sql

package db

import (
	"context"
	"database/sql"

	"vsc.irc.ugent.be/itsupport/work-in-peace/internal/db/sqlite"
)

const cancelAlarm = `-- name: CancelAlarm :one
UPDATE alarms SET cancelled_at = DATETIME('now')
WHERE alarm_id = ?
RETURNING alarm_id, user, created_at, deadline, cancelled_at, channel, description
`

func (q *Queries) CancelAlarm(ctx context.Context, alarmID int64) (Alarm, error) {
	row := q.db.QueryRowContext(ctx, cancelAlarm, alarmID)
	var i Alarm
	err := row.Scan(
		&i.AlarmID,
		&i.User,
		&i.CreatedAt,
		&i.Deadline,
		&i.CancelledAt,
		&i.Channel,
		&i.Description,
	)
	return i, err
}

const insertAlarm = `-- name: InsertAlarm :one
INSERT INTO alarms (user, deadline, description, channel)
VALUES (?, DATETIME(?, 'utc'), ?, ?)
RETURNING alarm_id, user, created_at, deadline, cancelled_at, channel, description
`

type InsertAlarmParams struct {
	User        string
	Datetime    interface{}
	Description sql.NullString
	Channel     string
}

func (q *Queries) InsertAlarm(ctx context.Context, arg InsertAlarmParams) (Alarm, error) {
	row := q.db.QueryRowContext(ctx, insertAlarm,
		arg.User,
		arg.Datetime,
		arg.Description,
		arg.Channel,
	)
	var i Alarm
	err := row.Scan(
		&i.AlarmID,
		&i.User,
		&i.CreatedAt,
		&i.Deadline,
		&i.CancelledAt,
		&i.Channel,
		&i.Description,
	)
	return i, err
}

const listActiveAlarms = `-- name: ListActiveAlarms :many
SELECT alarm_id, user, created_at, deadline, cancelled_at, channel, description FROM alarms WHERE cancelled_at IS NULL
`

func (q *Queries) ListActiveAlarms(ctx context.Context) ([]Alarm, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAlarms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alarm
	for rows.Next() {
		var i Alarm
		if err := rows.Scan(
			&i.AlarmID,
			&i.User,
			&i.CreatedAt,
			&i.Deadline,
			&i.CancelledAt,
			&i.Channel,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUserAlarms = `-- name: ListActiveUserAlarms :many
SELECT alarm_id, user, created_at, deadline, cancelled_at, channel, description FROM alarms WHERE user = ? AND cancelled_at IS NULL ORDER BY deadline ASC
`

func (q *Queries) ListActiveUserAlarms(ctx context.Context, user string) ([]Alarm, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUserAlarms, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alarm
	for rows.Next() {
		var i Alarm
		if err := rows.Scan(
			&i.AlarmID,
			&i.User,
			&i.CreatedAt,
			&i.Deadline,
			&i.CancelledAt,
			&i.Channel,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCancelledUserAlarms = `-- name: ListCancelledUserAlarms :many
SELECT alarm_id, user, created_at, deadline, cancelled_at, channel, description FROM alarms WHERE user = ? AND cancelled_at IS NOT NULL ORDER BY deadline DESC
`

func (q *Queries) ListCancelledUserAlarms(ctx context.Context, user string) ([]Alarm, error) {
	rows, err := q.db.QueryContext(ctx, listCancelledUserAlarms, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alarm
	for rows.Next() {
		var i Alarm
		if err := rows.Scan(
			&i.AlarmID,
			&i.User,
			&i.CreatedAt,
			&i.Deadline,
			&i.CancelledAt,
			&i.Channel,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAlarms = `-- name: ListUserAlarms :many
SELECT alarm_id, user, created_at, deadline, cancelled_at, channel, description FROM alarms WHERE user = ?
`

func (q *Queries) ListUserAlarms(ctx context.Context, user string) ([]Alarm, error) {
	rows, err := q.db.QueryContext(ctx, listUserAlarms, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alarm
	for rows.Next() {
		var i Alarm
		if err := rows.Scan(
			&i.AlarmID,
			&i.User,
			&i.CreatedAt,
			&i.Deadline,
			&i.CancelledAt,
			&i.Channel,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAlarm = `-- name: SelectAlarm :one
SELECT alarm_id, user, created_at, deadline, cancelled_at, channel, description FROM alarms WHERE alarm_id = ?
`

func (q *Queries) SelectAlarm(ctx context.Context, alarmID int64) (Alarm, error) {
	row := q.db.QueryRowContext(ctx, selectAlarm, alarmID)
	var i Alarm
	err := row.Scan(
		&i.AlarmID,
		&i.User,
		&i.CreatedAt,
		&i.Deadline,
		&i.CancelledAt,
		&i.Channel,
		&i.Description,
	)
	return i, err
}

const updateAlarmDeadline = `-- name: UpdateAlarmDeadline :one
UPDATE alarms SET deadline = ?
WHERE alarm_id = ?
RETURNING alarm_id, user, created_at, deadline, cancelled_at, channel, description
`

type UpdateAlarmDeadlineParams struct {
	Deadline sqlite.Time
	AlarmID  int64
}

func (q *Queries) UpdateAlarmDeadline(ctx context.Context, arg UpdateAlarmDeadlineParams) (Alarm, error) {
	row := q.db.QueryRowContext(ctx, updateAlarmDeadline, arg.Deadline, arg.AlarmID)
	var i Alarm
	err := row.Scan(
		&i.AlarmID,
		&i.User,
		&i.CreatedAt,
		&i.Deadline,
		&i.CancelledAt,
		&i.Channel,
		&i.Description,
	)
	return i, err
}
