// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alarms.sql

package db

import (
	"context"
	"database/sql"
)

const insertAlarm = `-- name: InsertAlarm :one
INSERT INTO alarms (user, deadline, description)
VALUES (?, DATETIME(?,'localtime'), ?)
RETURNING alarm_id, user, created_at, deadline, cancelled_at, description
`

type InsertAlarmParams struct {
	User        string
	Datetime    interface{}
	Description sql.NullString
}

func (q *Queries) InsertAlarm(ctx context.Context, arg InsertAlarmParams) (Alarm, error) {
	row := q.db.QueryRowContext(ctx, insertAlarm, arg.User, arg.Datetime, arg.Description)
	var i Alarm
	err := row.Scan(
		&i.AlarmID,
		&i.User,
		&i.CreatedAt,
		&i.Deadline,
		&i.CancelledAt,
		&i.Description,
	)
	return i, err
}
