// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
)

const insertChannel = `-- name: InsertChannel :one
INSERT INTO ntfy_channels (name, url)
VALUES (?, ?)
RETURNING channel_id, name, url
`

type InsertChannelParams struct {
	Name string
	Url  string
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (NtfyChannel, error) {
	row := q.db.QueryRowContext(ctx, insertChannel, arg.Name, arg.Url)
	var i NtfyChannel
	err := row.Scan(&i.ChannelID, &i.Name, &i.Url)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT channel_id, name, url FROM ntfy_channels
`

func (q *Queries) ListChannels(ctx context.Context) ([]NtfyChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NtfyChannel
	for rows.Next() {
		var i NtfyChannel
		if err := rows.Scan(&i.ChannelID, &i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChannel = `-- name: SelectChannel :one
SELECT channel_id, name, url FROM ntfy_channels WHERE name = ?
`

func (q *Queries) SelectChannel(ctx context.Context, name string) (NtfyChannel, error) {
	row := q.db.QueryRowContext(ctx, selectChannel, name)
	var i NtfyChannel
	err := row.Scan(&i.ChannelID, &i.Name, &i.Url)
	return i, err
}
