// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
)

const insertChannel = `-- name: InsertChannel :one
INSERT INTO ntfy_channels (name, url)
VALUES (?, ?)
RETURNING channel_id, name, url
`

type InsertChannelParams struct {
	Name string
	Url  string
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (NtfyChannel, error) {
	row := q.db.QueryRowContext(ctx, insertChannel, arg.Name, arg.Url)
	var i NtfyChannel
	err := row.Scan(&i.ChannelID, &i.Name, &i.Url)
	return i, err
}

const selectChannel = `-- name: SelectChannel :one
SELECT channel_id, name, url FROM ntfy_channels WHERE name = ?
`

func (q *Queries) SelectChannel(ctx context.Context, name string) (NtfyChannel, error) {
	row := q.db.QueryRowContext(ctx, selectChannel, name)
	var i NtfyChannel
	err := row.Scan(&i.ChannelID, &i.Name, &i.Url)
	return i, err
}
