// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eventlog.sql

package db

import (
	"context"
	"database/sql"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO eventlog
	(timestamp, user, type, subid, data)
VALUES
	(DATETIME('NOW'), ?, ?, ?, ?)
`

type InsertEventParams struct {
	User  string
	Type  string
	Subid sql.NullInt64
	Data  sql.NullString
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.User,
		arg.Type,
		arg.Subid,
		arg.Data,
	)
	return err
}
