// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Alarm struct {
	AlarmID     int64
	User        string
	CreatedAt   string
	Deadline    string
	CancelledAt sql.NullString
	Description sql.NullString
}

type Migration struct {
	MigrationID int64
	File        string
	Date        string
}

type NtfyChannel struct {
	ChannelID int64
	Url       string
}
