// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"vsc.irc.ugent.be/itsupport/work-in-peace/internal/db/sqlite"
)

type Alarm struct {
	AlarmID     int64
	User        string
	CreatedAt   sqlite.Time
	Deadline    sqlite.Time
	CancelledAt sqlite.NullTime
	Description sql.NullString
}

type Migration struct {
	MigrationID int64
	File        string
	Date        string
}

type NtfyChannel struct {
	ChannelID int64
	Url       string
}
