# MARKDOWN: table headers
regexp=^.*(\|[A-Z0-9\s]+\|[A-Z0-9\s]+\|).*$
colours=bold
-
# MARKDOWN: table divider
regexp=^.*(\|[\-\s]+\|[\-\s]+\|).*$
colours=strikethrough
-
# MARKDOWN: backticks
regexp=`([^`]+)`
colours=on_bright_white
-
regexp=DEBUG
colour=bold white
-
regexp=INFO
colour=bold blue
-
regexp=WARN
colour=bold yellow
-
regexp=ERROR
colour=bold red
-
regexp=(^|\s)([^=\s]+)=([^\s]+)
colours=default,italic blue,italic blue,green
-
regexp=(^|\s)([^=\s]+)="([^"]+)"
colours=default,italic blue,italic blue,green
-
regexp=(^make\[.*)
colours=italic white
-
regexp=(^>_.*)
colours=italic bold white
-
regexp=([\w/]+\.go:\d+:\d+.*)
colours=red
