# MARKDOWN: table headers
regexp=^.*(\|[A-Z0-9\s]+\|[A-Z0-9\s]+\|).*$
colours=bold
-
# MARKDOWN: table divider
regexp=^.*(\|[\-\s]+\|[\-\s]+\|).*$
colours=strikethrough
-
# MARKDOWN: backticks
regexp=`([^`]+)`
colours=on_bright_white
-
regexp=DEBUG
colour=bold white
-
regexp=INFO
colour=bold blue
-
regexp=WARN
colour=bold yellow
-
regexp=ERROR
colour=bold red
-
regexp=(^|\s)([^=\s]+)=([^\s]+)
colours=default,italic blue,italic blue,green
-
regexp=(^|\s)([^=\s]+)="([^"]+)"
colours=default,italic blue,italic blue,green
-
regexp=(^make\[.*)
colours=italic white
-
regexp=(^>_.*)
colours=italic bold white
-
regexp=(^>_ \*\*\* START MAKE\[0\].*)
colours=italic bold white reverse
-
regexp=([\w/]+\.go:\d+:\d+.*)
colours=red
-
### Tests
regexp=^not ok \d+.*$
color=red bold underline
-
regexp=^ok \d+.*$
color=green underline
-
regexp=^#.*$
color=white italic
-
regexp=(\s)(✓\s)(.)
color=default,default,on_green bright_white bold,on_green bright_white bold
replace=\1 \2 \3
-
regexp=<OK>
color=on_green bright_white bold
-
regexp=<FAILED>
color=on_red bright_white bold
-
regexp=(\s)(-\s)(.)
color=default,default,on_white black bold,on_white bright_white bold
replace=\1 \2 \3
-
regexp=(\s)(✗\s[^\[]*)
color=default,default,on_red bright_white bold,on_red bright_white bold
replace=\1 \2
